<?php

namespace GameaffinityBundle\Repository;

/**
 * DesarrolladoraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DesarrolladoraRepository extends \Doctrine\ORM\EntityRepository
{
}
