<?php

namespace GameaffinityBundle\Repository;

/**
 * JuegoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JuegoRepository extends \Doctrine\ORM\EntityRepository
{
    //Funcion que recupera de BD los juegos lanzados desde hoy hasta $amount dias atras
    public function findUltimosLanzamientos($amount_days){
        $em = $this->getEntityManager();
        
        $query = $em->createQuery(''
                . 'SELECT j, p, g, d '
                . 'FROM GameaffinityBundle:Juego j '
                . 'JOIN j.plataformas p '
                . 'JOIN j.generos g '
                . 'JOIN j.desarrolladora d '
                . 'WHERE j.fechaLanzamiento <= :fecha_hoy '
                . 'AND j.fechaLanzamiento >= :fecha_comparacion '
                . 'ORDER BY j.fechaLanzamiento DESC');
        
        $query->setParameter('fecha_hoy', new \DateTime('today'));
        $query->setParameter('fecha_comparacion', new \DateTime('today - ' . $amount_days . ' days'));
        
        return $query->getResult();
    }
}
