<?php

namespace GameaffinityBundle\Repository;

/**
 * NoticiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticiaRepository extends \Doctrine\ORM\EntityRepository
{
    //Funcion que recupera de BD las ultimas x ($amount) noticias
    public function findUltimasNoticias($amount){
        $em = $this->getEntityManager();
        
        $query = $em->createQuery(''
                . 'SELECT n, u '
                . 'FROM GameaffinityBundle:Noticia n '
                . 'JOIN n.autor u '
                . 'ORDER BY n.fechaPublicacion DESC ');
        
        $query->setMaxResults($amount);
        
        return $query->getResult();
    }
}
