<?php

namespace GameaffinityBundle\Repository;

/**
 * PlataformaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlataformaRepository extends \Doctrine\ORM\EntityRepository
{
}
