<?php

namespace GameaffinityBundle\Repository;

/**
 * PuntuacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PuntuacionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPuntuacionMedia($game_id){
        $em = $this->getEntityManager();
        
        $query = $em->createQuery(''
                . 'SELECT avg(p.nota) as promedio, j '
                . 'FROM GameaffinityBundle:Puntuacion p '
                . 'JOIN GameaffinityBundle:Juego j '
                . 'WHERE p.juego = :game_id');
        
        $query->setParameter('game_id', $game_id);
        return $query->getOneOrNullResult();
    }
}
